#!/usr/bin/env bash

echo "Running tests:"
npm run test-firefox && npm run test-chrome

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Tests must pass before commit."
 exit 1
fi